### ISSUE TITLE
Expanding panel

### ISSUE THREAD

**Issue by nkev** [vikignt/svelte-ui#12]
Thank you for sharing a great UI library. 

From my perspective after playing with it, I think the most obvious missing component is an expanding panel (like  animated sidepanel but vertical and not modal). For completeness, it should have 'groupName' and 'isAccordion' properties to display only current panel but hide all other panels in the same group, e.g. for sidenav vertical animation.

Do you have plans to add this?

**Comment by vikignt** [comment]
I wrote the [REPL](https://svelte.dev/repl/f303b220b0bb48ffbea40f10f6ee022e?version=3.15.0) as an example, you can write your own component using the idea

**Comment by nkev** [comment]
Thank you for writing that.

**Comment by sourcegr** [comment]
hey @vikignt , this is a really nice addition.

If you are planning to include it in the lib, I would also suggest an `onclose` handler, just like the `Dialog`s handler. Also, a way to customise the icon from the outside, would be nice.

In case you don't want to include it in the lib, I would suggest to leave this issue open and assign it a label - something like `recipes` - in order for others to find it easily.

**Comment by vikignt** [comment]
I will think, perhaps I will add a component
