### ISSUE TITLE
Template for sapper

### ISSUE THREAD

**Issue by manuel3108** [vikignt/svelte-ui#16]
I am trying to use this awesome package with sapper.
As of #1 apparently it is possible to use it.

Do you have any working template? It would be really nice to have one or get an hint to what we need to do to get it working

**Comment by vikignt** [comment]
Please upgrade `svelte-mui` to version 0.3.0 and import components from `svelte-mui/src`. Notify me if there are any problems.

**Comment by manuel3108** [comment]
I just tried it, but I am still getting the same error.
Do you have any other idea?

**Comment by vikignt** [comment]
I created an example [sapper-mui](https://github.com/vikignt/sapper-mui.git) from the [template](https://github.com/sveltejs/sapper-template) and then added a `svelte-mui` package. Try

```sh
git clone https://github.com/vikignt/sapper-mui.git
cd sapper-mui
npm ci
npm run dev
```

**Comment by manuel3108** [comment]
Thanks, this is working now. I used the webpack-template, thats propably the difference.
I think that `npm ci` is not necessary as its not in the `package.json`

Thanks for your help :D.

It might be helpful to link this repository in your readme

**Comment by vikignt** [comment]
I'm gonna try to repeat svelte-mui/example only with a sapper
