### ISSUE TITLE
Better import for Icon path's

### ISSUE THREAD

**Issue by manuel3108** [vikignt/svelte-ui#17]
I saw that you apparently copy & pasted all your icon's to local files.

A better way of doing this would be to `npm i @mdi/js` and then do the following:
```html
<Button icon>
	<Icon path={mdiInvertColors} />
</Button>

<script>
	import { mdiInvertColors } from '@mdi/js'
</script>
```

You can get the Icon names from here [materialdesignicons.com](https://materialdesignicons.com/)

**Comment by vikignt** [comment]
Thank you, the resource [materialdesignicons.com](https://materialdesignicons.com) is great, but for this example it's huge.
I used my converter from [material-design-icons](https://github.com/google/material-design-icons)

**Comment by manuel3108** [comment]
Ok, I just thought that this might be an easier way to use those icons. But I understand your concerns.
