### ISSUE TITLE
Add some guidance / docs regarding a CSS strategy

### ISSUE THREAD

**Issue by ispyinternet** [vikignt/svelte-ui#21]
For example, i'm currently digging around the code to understand how to set the default primary and accent. Could the colour properties accept css var style inputs?

for example `<Checkbox color={--color-primary}>`

Basically looking for a good CSS story!

**Comment by vikignt** [comment]
You can use any valid css color, for example

```html
<script>
  let myColor="blue";
</script>

<Checkbox color="red">checkbox red</Checkbox>
<Checkbox color="#00ff00">checkbox green</Checkbox>
<Checkbox color={myColor}>checkbox blue</Checkbox>
```

or reassign css var `--primary` (default) or `--accent`, see example with css class #20

Let me know if you have any problems.

**Comment by ispyinternet** [comment]
Yh but how can you control site wide theming, like primary accent colours?

**Comment by ispyinternet** [comment]
Ah ok, you fall back to css vars  —primary etc.
