### ISSUE TITLE
Button raised or unleveled property cause Error: Invalid HEX color!

### ISSUE THREAD

**Issue by trufa2017** [vikignt/svelte-ui#22]
Hi, thanks for this great work.
My button looks like this:
`<Button raised> Hi</Button>`
`<Button unelevated> Hi</Button>`

and throws error in :
in file : lib>colors.js
in line 56 , throws new error   Error: Invalid HEX color!

**Comment by vikignt** [comment]
Thank you. This problem has been solved [d4f1fed](https://github.com/vikignt/svelte-mui/commit/d4f1fed707c530c662a217371b0f398b23f6e7e9), but not yet published on `npm`. I will publish it in the next few days.

**Comment by vikignt** [comment]
Ok. v0.3.3 has been published. Try it, and if you have any problems let me know.

**Comment by trufa2017** [comment]
That was super fast response, thank you very much vikignt, raised now works perfectly !
