### ISSUE TITLE
filled Textfield background

### ISSUE THREAD

**Issue by subhasishdas159** [vikignt/svelte-ui#24]
When using the textfield is "filled" mode the background is too much dark when focused on the textfield and, as a result the text becomes harder to read for elderly people.

I also saw this dark gray background in material components for the web. 

It would be helpful if it could be made a little bit lighter in color so that the contrast between the foreground and the background remains high.

**Comment by vikignt** [comment]
You can try to change custom CSS property `--bg-input-filled`, for example

```html
<Textfield class="myfilled" />

<style>
    /* focus only */
    :global(.myfilled) .input:focus {
        --bg-input-filled: rgba(255, 255, 255, 0.3);
    }
</style>
```
