### ISSUE TITLE
Menu component doesn't hide on click outside

### ISSUE THREAD

**Issue by igolkotek** [vikignt/svelte-ui#3]
Hi, vikignt,
You do so nice component library, thank you.
I checked Menu from demo page with browsers on android, desktop and ios.
Menu is hiding on click outside menu as it should in every browser but iOS Safari 12.1 on iPad.

**Comment by vikignt** [comment]
Thank you, aiia,
I am tested on Simulator iOS Safari 13 Beta and menu worked well, I will check it on iOS 12.

**Comment by vikignt** [comment]
menu popup close by scroll on touch devices

**Comment by igolkotek** [comment]
I'm not sure this is a bug: touching outside menu closes as it must. But if scrolling is done by touching a point within menu, it doesn't close.
It looks OK for me.

**Comment by vikignt** [comment]
iOS devices behave like android

**Comment by vikignt** [comment]
Set cursor pointer on iOS devices only
