### ISSUE TITLE
Cannot find instructions on installation

### ISSUE THREAD

**Issue by thompcd** [vikignt/svelte-ui#4]
You have a great looking library, I'd love to try it out! Does it happen to live on NPM?

**Comment by vikignt** [comment]
Hello @thompcd

Thank you for your interest. I think that it is too early to publish on NPM, You can try install library from `github`. Simple example of using

```sh
# create a new project based on template
npx degit sveltejs/template svelte-app
cd svelte-app
npm i
# add UI components as devDependencies
npm i -D git+https://git@github.com/vikignt/svelte-ui.git
```

modify `src/App.svelte` file

```html
<script>
	export let name;

	import { Button, Checkbox } from 'svelte-ui';
	let checked = true;
</script>

<style>
	h1 {
		color: purple;
	}
</style>

<h1>Hello {name}!</h1>

<Checkbox bind:checked>Checkbox</Checkbox>
<p>Checkbox is <strong>{checked ? 'checked' : 'unchecked'}</strong></p>
<Button outlined shaped color="Red" on:click={() => { checked = !checked }}>Inverse</Button>
```

then start

```sh
npm run dev
```

You can add [focus-visible](https://github.com/WICG/focus-visible) polyfill to app, if you need visible focus by <kbd>TAB</kbd>

```sh
npm i -D focus-visible
```

and import it once on top of the `main.js` file, like this

```js
import 'focus-visible';
import App from './App.svelte';
.
.
```
