### ISSUE TITLE
Datepicker weekday labels are off by 3

### ISSUE THREAD

**Issue by ellemenno** [vikignt/svelte-ui#43]
## using

```html
<Datepicker value={new Date()} locale="en" />
```

### expected weekday labels

for `en` locale, week typically starts on Sunday:

**S  M  T  W  T  F  S**

### actual weekday labels

week is labelled as starting on Thursday:
**T  F  S  S  M  T  W**

note that the day numbers are in the expected positions, just the labels are shifted.

## repro examples

Svelte REPL: https://svelte.dev/repl/90ad3ec1deec4416ab3d6c2e601aa113?version=3.35.0

![weekday-labels](https://user-images.githubusercontent.com/317494/112722020-7febab80-8edd-11eb-9549-3e1cb9de1c69.png)

**Comment by vikignt** [comment]
Hi, everything seems to be fine in your REPL.

<img width="488" alt="Screenshot 2021-03-28 at 12 17 19" src="https://user-images.githubusercontent.com/1016829/112747676-936f4300-8fbf-11eb-974e-ce7e8324e7db.png">

What browser do you use?
Please, check for errors in the developer tools console.

**Comment by ellemenno** [comment]
sorry for the delayed reply. i've rechecked and get the same results (day labels starting week on Thursday instead of Sunday) across several different devices.

i experience the same results with the [datepicker demo](https://svelte-mui.vercel.app/datepicker) as well, but i created the repl to double check on as vanilla a setup as possible:

Windows 10 laptop
- Google Chrome `v89.0.4389.114`, `v90.0.4430.72`
- Microsoft Edge `v89.0.774.77`, `v90.0.818.41`

Google Pixel 5 phone
- Google Chrome `v89.0.4389.105`

Apple MacBook
- Google Chrome `v90.0.4430.72`
- Safari `v12.1.2 (12607.3.10)`

in each case there are no errors in the javascript console, and `navigator.languages` returns `["en-US", "en"]` or `["en-US"]`

**Comment by ellemenno** [comment]
looking at the code in [`src/datepicker/Day.svelte#L108`](https://github.com/vikignt/svelte-mui/blob/master/src/datepicker/Day.svelte#L108), i can recreate both what i'm seeing and what i'd like to see:

```js
let test = (date, weekStart, locale='en') => {
  let weekdays = [];
  for (let i = 0; i < 7; i++) {
    date.setDate(4 + weekStart + i);
    weekdays.push(
      new Intl.DateTimeFormat(locale, {
        weekday: 'narrow',
      }).format(date)
    );
  }
  return weekdays;
}
```

```js
test(new Date(0), 0); //  ["T", "F", "S", "S", "M", "T", "W"]  <-- actual
test(new Date(), 0);  //  ["S", "M", "T", "W", "T", "F", "S"]  <-- expected
test(new Date(0), 3); //  ["S", "M", "T", "W", "T", "F", "S"]  <-- expected
```

i notice that `weekStartOne` on L85 does not include `en` (only `en-SG en-au en-gb en-ie en-nz`), so if my locale is `en-US` or `en`, then it will fall through the checks starting on L94 and end up with  `weekStart = 0` on L103.

in my quick test above, the combination of `new Date(0)` and `weekStart == 0` results in the week labels starting on Thursday as observed.

initializing the new Date without any parameters generates the week labels starting on Sunday as desired. alternatively, `new Date(0)` with `weekStart == 3` would also give desired results.

**Comment by NiAlvarez** [comment]
Same issue is happening on all my devices, any new update?

**Comment by knoxjoseph** [comment]
> ## using
> ```
> <Datepicker value={new Date()} locale="en" />
> ```
> 
> ## results
> ### expected weekday labels
> for `en` locale, week typically starts on Sunday:
> 
> **S M T W T F S**
> 
> ### actual weekday labels
> week is labelled as starting on Thursday:
> **T F S S M T W**
> 
> note that the day numbers are in the expected positions, just the labels are shifted.
> 
> ## repro examples
> Svelte REPL: https://svelte.dev/repl/90ad3ec1deec4416ab3d6c2e601aa113?version=3.35.0
> 
> ![weekday-labels](https://user-images.githubusercontent.com/317494/112722020-7febab80-8edd-11eb-9549-3e1cb9de1c69.png)

Hey @ellemenno your REPL works fine for me as well.
![image](https://user-images.githubusercontent.com/15373911/120584621-ee089d80-c44d-11eb-87e0-bf871083c411.png)

Perhaps some locale issue?
