### ISSUE TITLE
svelte-mui does not work with svelte version 3.41

### ISSUE THREAD

**Issue by annekekleppe** [vikignt/svelte-ui#46]
Apparently, the function get_slot_context is no longer exported from svelte version 3.41.*, which creates the following error message:
Error: 'get_slot_context' is not exported by ..\..\node_modules\svelte\internal\index.mjs, imported by ..\..\node_modules\svelte-mui\index.mjs

I have gone back to svelte 3.38.*, and then everything works fine.

Thanks for svelte-mui, I hope you can take up this issue anytime soon.

**Comment by joswarmer** [comment]
Hi, I see little activity in the project, is there any chance that this will be fixed? 

Tnx, Jos

**Comment by joswarmer** [comment]
I took a look at the sources and found that the offending get_slot_context is never imported nor used  in svelte-mui. So it is probably a packaging or configuration problem why this ends up in the index.mjs file.
As I cannot get the project to build, I am stuck.

**Comment by joswarmer** [comment]
@vikignt Tnx! We can now upgrade to the latest Svelte version.

**Comment by joswarmer** [comment]
Closing this, works again.

**Comment by annekekleppe** [comment]
Thanks! Good to see this project being maintained.
