### ISSUE TITLE
Checkbox and Radio emits on:click twice

### ISSUE THREAD

**Issue by sourcegr** [vikignt/svelte-ui#5]
First of all, congratulations for your work :)
Small, efficient, and to the point.

To the issue... As the title says, clicking on a Radio or Checkbox control, emits the on:click handler twice.

Please see the following example

https://codesandbox.io/s/svelte-ui-radio-5ioso?fontsize=14

**Comment by vikignt** [comment]
Thanks @sourcegr to your attention, this is my fault. use:events must be set to the input element.

**Comment by sourcegr** [comment]
But if you move it to the input element, you loose all the `onmouseover`, `onmouseenter` and such event handlers which are very useful!

**Comment by vikignt** [comment]
Yes, you are right, but otherwise, we lose `focus`, `blur`, need a compromise.
